export const symbolMap = {
  '™': '',
  '∅': '',
  '—': '-',
  '•': '-',
  '‘': "'",
  '₂': '2',
  '¹⁷': ' to the power 17',
  '¹': '1',
  '²': '2',
  '³': '3',
  Ω: 'ohms',
  '±': ' plus or minus ',
  '°': ' deg ',
  '“': '',
  '”': '',
  '″': 'inches ',
  '®': '',
  '©': '',
  '⎓': '',
  '×': 'x',
  '△': '',
  µs: 'microseconds',
  ' ‎': ' ',
  '\u200e': ' ',
  º: 'deg ',
  '.': '.',
  '\u2024': '.',
  '\u2025': '.',
  '\u2019': "'",
  '\u2013': '-',
  '≤': ' less than ',
  '≥': ' greater than ',
  '≦': ' less than or equal to ',
  '≧': ' greater than or equal to ',
  '\u00a0': ' ',
  '\u00e2': '',
  '€': '',
  ª: '',
  '℃': ' degC',
  '℉': ' degF',
  '◦C': ' degC'
}

export const syntechCategoryReplacements = [
  ['Computers & Peripherals', 'Peripherals'],
  ['Consumer Electronics > ', 'Accessories > '],
  ['Peripherals > Desktop Computers > Gaming Desktops', 'Computers > Gaming Desktops'],
  ['Peripherals > Desktop Computers > Office Desktops', 'Computers > Office Desktops'],
  ['Peripherals > Mini PCs > Barebone Systems', 'Mini PCs > Barebone Systems'],
  ['Peripherals > Mini PCs > Complete Systems', 'Mini PCs > Complete Systems'],
  ['Peripherals > Mousepads', 'Accessories > Mousepads'],
  ['Peripherals > Stands and Cooling', 'Accessories > Stands and Cooling'],
  ['Accessories > Bags and Covers', 'Accessories > Bags and Covers'],
  ['Heating, Cooling, and Air Quality', 'Heating Cooling and Air Quality'],
  ['Appliances > ', 'Gadgets > '],
  [
    'Peripherals > Computer Audio > Headsets',
    'Peripherals > Computer Audio > Headsets > Over-Ears'
  ],
  ['Accessories > Headphones > ', 'Peripherals > Computer Audio > Headsets > '],
  ['Accessories > Lighting', 'Gadgets > Lighting'],
  ['Accessories > Portable Printing > Printers', 'Printers > Portable Printers'],
  [
    'Accessories > Portable Printing > Printing Consumables',
    'Printers > Portable Printers > Consumables'
  ],
  ['Accessories > Speakers', 'Peripherals > Computer Audio > Speakers'],
  [
    'Accessories > Media and Streaming > Adapters and Converters',
    'Peripherals > Adapters > Display Adapters'
  ],
  ['Networking & Security > ', 'Networking > ']
]

export const syntechUnwantedSubstrings = [
  'Coming Soon',
  // 'On Promotion',
  'Just Arrived',
  'Unboxed',
  'Last Chance',
  'Apparel',
  'Hydroponics',
  ' > Mounts and Brackets',
  ' > Screen Protectors',
  ' > Cables',
  ' > Tools',
  ' > Mounts and Brackets',
  ' > Screen Protectors',
  ' > Mobile Devices > Stylus',
  ' > Smart Security',
  ' > Scooters and Bikes',
  ' > Wearables > Accessories',
  ' > Lifestyle Accessories'
]

export const micropointUnwantedSubstrings = [
  'ACCESS POINT',
  'AA STOCK CLEARANCE >',
  'BATTERIES >',
  'BLUETOOTH DEVICES >',
  'BUNDLES >',
  'CAMERAS >',
  'CARTRIDGES >',
  'CASES >',
  'CCTV >',
  'CONSUMABLES >',
  'CONVERTER BOXES >',
  'DESKTOP MACHINE >',
  'DVI PRODUCTS >',
  'EXTENDERS >',
  'EXTERNAL ENCLOSURES >',
  'FANS >',
  'FLEA MARKET >',
  'FOR SUPPLIER STOCK PURPOSES >',
  'HARD DRIVES > NOTE BOOK DRIVE CADDY',
  'HARD DRIVES > REFURBISHED STOCK',
  'HARD DRIVES > SUPPLIER STOCK',
  'HEALTHCARE >',
  'KVM SWITCHES >',
  'LAN PRODUCTS >',
  'LOGITECH >',
  'MEDIA PLAYERS >',
  'MINING >',
  'MT-VIKI >',
  'MULTIPLUGS >',
  'NETWORK CABLE >',
  'NETWORKING > ADSL MODEMS / ROUTERS',
  'NETWORKING > CABLES',
  'NETWORKING > CAT6 CABLES',
  'NETWORKING > KVM SWITCHES',
  'NETWORKING > MEDIA CONVERTERS',
  'NETWORKING > POWER OF ETHERNET',
  'NETWORKING > USB',
  'NOT FOR LISTING >',
  'NOTEBOOK BAGS > CAMERA',
  'NOTEBOOKS > REFURBISHED STOCK',
  'NOTEBOOKS > WARRANTY',
  'OPTICAL DRIVES >',
  'ORICO ITEMS >',
  'PARTS >',
  'PARTS FOR REPAIRING >',
  'POINT OF SALE >',
  'POWER SUPPLY >',
  'PRINTERS >',
  'PROCESSORS > THERMAL PASTE',
  'PROJECTORS >',
  'REFURBISHED >',
  'ROUTERS >',
  'SANITIZER >',
  'SERVERS >',
  'SLEEVE >',
  'SOLID STATE DRIVE >',
  'TOOLS >',
  'TP-LINK >',
  'TRANSMITTERS >',
  'TV >',
  'WARRANTY >',
  'MICROSOFT > SERVER',
  'PHILIPS >',
  'PHONES >',
  'PROCESSORS >',
  'UPS > ACCESSORIES',
  'MOUSE > GAMING',
  'MOUSE > ACCESSORIES',
  'MEMORY > MEMORY'
  // /mouse > $/giu
]

export const micropointAcronyms = new Set([
  'USB',
  'HDMI',
  'OTG',
  'VGA',
  'DVI',
  'RCA',
  'PS2',
  'PCI-E',
  'PCMCIA',
  'PCI',
  'MSATA',
  'HDD',
  'LDINO',
  'KVM',
  'IDE',
  'SAS',
  'RJ11',
  'CAT',
  'CPU',
  'SSD',
  'AMD',
  'ATI',
  'AM2'
])
